repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.5.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
