apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-comment-ops.fullname" . }}
  labels:
    {{- include "github-comment-ops.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_APP_PRIVATE_KEY: {{ .Values.github.app_private_key | b64enc}}
  WEBHOOK_SECRET: {{ .Values.github.webhook_secret | b64enc }}
